# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "CI lane: run tests, bundle JS, build APK locally"
  lane :ci do
    # Run unit tests
    gradle(task: "test")

    # Bundle React Native JS
    sh "npx react-native bundle --entry-file index.js --platform android --dev false --bundle-output ./build/index.android.bundle"

    # Build APK locally (no upload)
    gradle(task: "clean assembleRelease")
  end
end