name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  react-native-ci:
    if: contains(github.event.head_commit.message, '[ci]') # only run on [ci] commits
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [ios, android]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm install
      
      # Cache Gradle (Android only)
      - name: Cache Gradle
        if: matrix.platform == 'android'
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

        # Setup Ruby + Bundler (for Fastlane)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true
          bundler: latest

      - name: Install Fastlane
        run: brew install fastlane

        # Run Fastlane lane
      - name: Run Fastlane lane
        run: |
          if [ "${{ matrix.platform }}" == "ios" ]; then
            cd ios
            fastlane ci
            cd ..
          else
            cd android
            fastlane ci
            cd ..
          fi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: ./build/*